- name: Run PostgreSQL container
  community.docker.docker_container:
    name: my_postgres
    image: buhsnn/tp-devops-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "{{ SPRING_DATASOURCE_PASSWORD }}"
      POSTGRES_USER: "{{ SPRING_DATASOURCE_USERNAME }}"
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - name: my_app_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
