---
# tasks file for ansible/roles/docker_network
- name: Create Docker network
  community.docker.docker_network:
    name: my_app_network
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

