---
# tasks file for ansible/roles/proxy
- name: Run HTTPD proxy container
  community.docker.docker_container:
    name: my_proxy
    image: buhsnn/tp-devops-http-server:latest
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    networks:
      - name: my_app_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
