name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Ou ta branche de production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy with Ansible via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/admin/mon-projet/ansible  # Remplace par le chemin réel sur le serveur
            ansible-playbook -i inventories/setup.yml deploy.yml
